version: "3.9"
networks:
  myAppNetwork:
    driver: bridge

services:
  app:
    container_name: pv311-native-api-container
    image: novakvova/pv311-native-api
    ports:
      - "5180:8080"  
    networks:
      - myAppNetwork
    volumes:
      - /data/pv311-native-api/images:/app/images
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

